"""Loan catalog for Tier 8 module."""

RAW_LOAN_CATALOG = [
    {
        "loan_id": "HL_001",
        "parent_type": "Home Loan",
        "subtype": "Home Purchase",
        "use_case_tags": ["house", "home", "property", "flat", "apartment", "purchase"],
        "use_case_description": "For buying a ready-to-move residential property such as a flat, apartment, or independent house. Suitable for salaried and self-employed borrowers seeking long-tenure EMIs. Includes funding for registration and select ancillary purchase costs.",
        "min_amount": 1_000_000,
        "max_amount": 50_000_000,
        "min_tenure_months": 120,
        "max_tenure_months": 360,
        "base_rate": 8.50,
        "max_rate": 11.00,
        "processing_fee_pct": 0.50,
        "processing_fee_floor_inr": 10_000,
        "ltv_cap": 0.80,
        "collateral_required": True,
        "min_credit_score": 700,
        "max_foir": 0.50,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [180, 240, 300, 360],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "HL_002",
        "parent_type": "Home Loan",
        "subtype": "Home Construction",
        "use_case_tags": ["construction", "plot", "house", "build", "residential"],
        "use_case_description": "For borrowers constructing a house on owned or jointly owned land. Disbursement can be stage-based according to construction milestones. Designed for borrowers who need flexibility during build phases.",
        "min_amount": 1_000_000,
        "max_amount": 40_000_000,
        "min_tenure_months": 120,
        "max_tenure_months": 360,
        "base_rate": 8.70,
        "max_rate": 11.20,
        "processing_fee_pct": 0.60,
        "processing_fee_floor_inr": 10_000,
        "ltv_cap": 0.75,
        "collateral_required": True,
        "min_credit_score": 700,
        "max_foir": 0.50,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [180, 240, 300, 360],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "HL_003",
        "parent_type": "Home Loan",
        "subtype": "Home Improvement / Renovation",
        "use_case_tags": ["renovation", "improvement", "interiors", "repair", "home"],
        "use_case_description": "For renovation, extension, or structural improvement of an existing home. Useful for kitchen upgrades, waterproofing, repainting, and civil work. Loan terms are shorter than purchase loans and suited for moderate ticket sizes.",
        "min_amount": 500_000,
        "max_amount": 10_000_000,
        "min_tenure_months": 60,
        "max_tenure_months": 240,
        "base_rate": 9.00,
        "max_rate": 11.50,
        "processing_fee_pct": 0.75,
        "processing_fee_floor_inr": 7_500,
        "ltv_cap": 0.70,
        "collateral_required": True,
        "min_credit_score": 690,
        "max_foir": 0.50,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [84, 120, 180, 240],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "VL_001",
        "parent_type": "Vehicle Loan",
        "subtype": "New Car Loan",
        "use_case_tags": ["car", "vehicle", "auto", "new", "sedan", "suv"],
        "use_case_description": "For financing brand-new passenger vehicles purchased from authorized dealers. Covers private-use and select business-use cases depending on profile. Structured with shorter tenure and faster sanction cycles.",
        "min_amount": 100_000,
        "max_amount": 4_000_000,
        "min_tenure_months": 12,
        "max_tenure_months": 84,
        "base_rate": 8.75,
        "max_rate": 13.00,
        "processing_fee_pct": 1.00,
        "processing_fee_floor_inr": 3_000,
        "ltv_cap": 0.90,
        "collateral_required": True,
        "min_credit_score": 680,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [24, 36, 48, 60, 84],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "VL_002",
        "parent_type": "Vehicle Loan",
        "subtype": "Used Car Loan",
        "use_case_tags": ["used car", "pre-owned", "second hand", "car", "vehicle"],
        "use_case_description": "For purchasing certified pre-owned cars from dealers or verified sellers. Eligibility depends on borrower profile and vehicle age. Best suited for customers looking for lower on-road cost entry.",
        "min_amount": 50_000,
        "max_amount": 1_500_000,
        "min_tenure_months": 12,
        "max_tenure_months": 60,
        "base_rate": 10.50,
        "max_rate": 15.00,
        "processing_fee_pct": 1.25,
        "processing_fee_floor_inr": 2_500,
        "ltv_cap": 0.80,
        "collateral_required": True,
        "min_credit_score": 650,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [18, 24, 36, 48, 60],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "VL_003",
        "parent_type": "Vehicle Loan",
        "subtype": "Two-Wheeler Loan",
        "use_case_tags": ["bike", "scooter", "motorcycle", "two wheeler", "vehicle"],
        "use_case_description": "For financing motorcycles and scooters for personal commute. Ideal for first-time credit users due to smaller ticket sizes. Quick approvals with streamlined documentation in many cases.",
        "min_amount": 20_000,
        "max_amount": 200_000,
        "min_tenure_months": 12,
        "max_tenure_months": 36,
        "base_rate": 12.00,
        "max_rate": 18.00,
        "processing_fee_pct": 1.50,
        "processing_fee_floor_inr": 1_000,
        "ltv_cap": 0.85,
        "collateral_required": True,
        "min_credit_score": 620,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [12, 18, 24, 30, 36],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "PL_001",
        "parent_type": "Personal Loan",
        "subtype": "Salaried Personal Loan",
        "use_case_tags": ["personal", "salary", "wedding", "travel", "expense"],
        "use_case_description": "Unsecured personal loan for salaried borrowers to manage planned or urgent expenses. Suitable for wedding costs, travel, or household needs. Offers quick disbursement for eligible profiles.",
        "min_amount": 25_000,
        "max_amount": 4_000_000,
        "min_tenure_months": 12,
        "max_tenure_months": 60,
        "base_rate": 11.00,
        "max_rate": 18.00,
        "processing_fee_pct": 2.00,
        "processing_fee_floor_inr": 2_000,
        "ltv_cap": None,
        "collateral_required": False,
        "min_credit_score": 700,
        "max_foir": 0.50,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [12, 24, 36, 48, 60],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "PL_002",
        "parent_type": "Personal Loan",
        "subtype": "Self-Employed Personal Loan",
        "use_case_tags": ["personal", "self employed", "cash flow", "expense", "urgent"],
        "use_case_description": "Unsecured personal borrowing option for self-employed professionals and business owners. Useful for short-term personal cash-flow support. Underwriting emphasizes income stability and repayment behavior.",
        "min_amount": 25_000,
        "max_amount": 3_000_000,
        "min_tenure_months": 12,
        "max_tenure_months": 60,
        "base_rate": 11.75,
        "max_rate": 18.50,
        "processing_fee_pct": 2.25,
        "processing_fee_floor_inr": 2_500,
        "ltv_cap": None,
        "collateral_required": False,
        "min_credit_score": 700,
        "max_foir": 0.50,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [12, 24, 36, 48, 60],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "PL_003",
        "parent_type": "Personal Loan",
        "subtype": "Medical Emergency Loan",
        "use_case_tags": ["medical", "hospital", "emergency", "treatment", "surgery"],
        "use_case_description": "Emergency unsecured loan for hospitalization, surgery, or urgent treatment expenses. Designed for fast underwriting and quicker release. Best for short-to-medium tenure repayment plans.",
        "min_amount": 25_000,
        "max_amount": 1_000_000,
        "min_tenure_months": 12,
        "max_tenure_months": 36,
        "base_rate": 13.00,
        "max_rate": 20.00,
        "processing_fee_pct": 1.50,
        "processing_fee_floor_inr": 1_500,
        "ltv_cap": None,
        "collateral_required": False,
        "min_credit_score": 650,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [12, 18, 24, 30, 36],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "GL_001",
        "parent_type": "Gold Loan",
        "subtype": "Gold Ornament Loan",
        "use_case_tags": ["gold", "ornament", "jewellery", "pledge", "secured"],
        "use_case_description": "Secured short-tenure funding against household gold ornaments. Offers quick disbursement with minimal paperwork compared to unsecured products. Commonly used for emergency liquidity needs.",
        "min_amount": 10_000,
        "max_amount": 5_000_000,
        "min_tenure_months": 6,
        "max_tenure_months": 36,
        "base_rate": 9.00,
        "max_rate": 14.00,
        "processing_fee_pct": 0.75,
        "processing_fee_floor_inr": 500,
        "ltv_cap": 0.75,
        "collateral_required": True,
        "min_credit_score": 600,
        "max_foir": 0.60,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [6, 12, 18, 24, 36],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "GL_002",
        "parent_type": "Gold Loan",
        "subtype": "Gold Coin / Bar Loan",
        "use_case_tags": ["gold coin", "gold bar", "bullion", "secured", "pledge"],
        "use_case_description": "Secured funding against verified gold coins or bars, subject to purity and source checks. Suitable for borrowers requiring quick short-term capital. Loan amount is directly constrained by LTV and collateral valuation.",
        "min_amount": 25_000,
        "max_amount": 5_000_000,
        "min_tenure_months": 6,
        "max_tenure_months": 36,
        "base_rate": 9.25,
        "max_rate": 14.50,
        "processing_fee_pct": 0.90,
        "processing_fee_floor_inr": 750,
        "ltv_cap": 0.75,
        "collateral_required": True,
        "min_credit_score": 600,
        "max_foir": 0.60,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [6, 12, 18, 24, 36],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "EL_001",
        "parent_type": "Education Loan",
        "subtype": "Domestic Education Loan",
        "use_case_tags": ["education", "college", "fees", "university", "course", "india"],
        "use_case_description": "For tuition, hostel, books, and related expenses for studies within India. Applicable for undergraduate and postgraduate programs at recognized institutions. Moratorium structures may be supported depending on policy.",
        "min_amount": 200_000,
        "max_amount": 2_000_000,
        "min_tenure_months": 60,
        "max_tenure_months": 180,
        "base_rate": 9.50,
        "max_rate": 12.00,
        "processing_fee_pct": 1.00,
        "processing_fee_floor_inr": 2_000,
        "ltv_cap": None,
        "collateral_required": False,
        "min_credit_score": 650,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [84, 120, 144, 180],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "EL_002",
        "parent_type": "Education Loan",
        "subtype": "International Education Loan",
        "use_case_tags": ["abroad", "international", "education", "university", "masters", "mbbs"],
        "use_case_description": "For funding higher studies overseas including tuition and living expenses. Supports large ticket sizes for global universities and professional courses. Underwriting considers co-applicant profile and repayment capacity.",
        "min_amount": 1_000_000,
        "max_amount": 7_500_000,
        "min_tenure_months": 60,
        "max_tenure_months": 180,
        "base_rate": 10.50,
        "max_rate": 13.50,
        "processing_fee_pct": 1.20,
        "processing_fee_floor_inr": 5_000,
        "ltv_cap": None,
        "collateral_required": False,
        "min_credit_score": 680,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [84, 120, 144, 180],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "BL_001",
        "parent_type": "Business Loan",
        "subtype": "MSME / Small Business Loan",
        "use_case_tags": ["business", "msme", "shop", "startup", "expansion"],
        "use_case_description": "For MSMEs and small businesses seeking funds for expansion, inventory, and operational scaling. Typically unsecured or lightly secured based on profile. Useful for growth-stage working businesses with regular turnover.",
        "min_amount": 100_000,
        "max_amount": 20_000_000,
        "min_tenure_months": 12,
        "max_tenure_months": 84,
        "base_rate": 11.00,
        "max_rate": 16.00,
        "processing_fee_pct": 1.50,
        "processing_fee_floor_inr": 5_000,
        "ltv_cap": None,
        "collateral_required": False,
        "min_credit_score": 680,
        "max_foir": 0.60,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [24, 36, 48, 60, 84],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "BL_002",
        "parent_type": "Business Loan",
        "subtype": "Working Capital Loan",
        "use_case_tags": ["working capital", "inventory", "cash flow", "business", "operations"],
        "use_case_description": "Short-tenure credit line or term loan for day-to-day business liquidity needs. Helps manage receivable cycles, payroll, and seasonal inventory requirements. Built for faster turnaround and frequent utilization.",
        "min_amount": 50_000,
        "max_amount": 5_000_000,
        "min_tenure_months": 6,
        "max_tenure_months": 36,
        "base_rate": 13.00,
        "max_rate": 19.00,
        "processing_fee_pct": 1.25,
        "processing_fee_floor_inr": 3_000,
        "ltv_cap": None,
        "collateral_required": False,
        "min_credit_score": 670,
        "max_foir": 0.60,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [6, 12, 18, 24, 36],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "BL_003",
        "parent_type": "Business Loan",
        "subtype": "Equipment / Machinery Loan",
        "use_case_tags": ["machinery", "equipment", "plant", "manufacturing", "business"],
        "use_case_description": "For purchasing industrial machinery, production equipment, or specialized business assets. Structured with asset-backed lending norms and defined repayment periods. Useful for capacity addition and productivity enhancement.",
        "min_amount": 200_000,
        "max_amount": 10_000_000,
        "min_tenure_months": 24,
        "max_tenure_months": 84,
        "base_rate": 10.50,
        "max_rate": 15.00,
        "processing_fee_pct": 1.25,
        "processing_fee_floor_inr": 4_000,
        "ltv_cap": 0.80,
        "collateral_required": True,
        "min_credit_score": 680,
        "max_foir": 0.60,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [24, 36, 48, 60, 84],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "LAP_001",
        "parent_type": "LAP",
        "subtype": "Residential Property LAP",
        "use_case_tags": ["lap", "loan against property", "residential", "mortgage", "property"],
        "use_case_description": "Secured borrowing against residential property ownership for large personal or business needs. Offers larger ticket sizes and longer tenure than unsecured loans. Property valuation and legal checks are mandatory.",
        "min_amount": 1_000_000,
        "max_amount": 50_000_000,
        "min_tenure_months": 60,
        "max_tenure_months": 240,
        "base_rate": 10.00,
        "max_rate": 13.00,
        "processing_fee_pct": 1.00,
        "processing_fee_floor_inr": 15_000,
        "ltv_cap": 0.60,
        "collateral_required": True,
        "min_credit_score": 700,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [84, 120, 180, 240],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "LAP_002",
        "parent_type": "LAP",
        "subtype": "Commercial Property LAP",
        "use_case_tags": ["lap", "commercial property", "mortgage", "business premise", "secured"],
        "use_case_description": "Loan against owned commercial property such as shops, offices, or mixed-use units. Designed for higher-value borrowing where property-backed security is available. Includes stricter valuation and title diligence.",
        "min_amount": 2_000_000,
        "max_amount": 100_000_000,
        "min_tenure_months": 60,
        "max_tenure_months": 180,
        "base_rate": 11.00,
        "max_rate": 14.00,
        "processing_fee_pct": 1.25,
        "processing_fee_floor_inr": 20_000,
        "ltv_cap": 0.55,
        "collateral_required": True,
        "min_credit_score": 700,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [84, 120, 144, 180],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
    {
        "loan_id": "LAP_003",
        "parent_type": "LAP",
        "subtype": "Plot / Land LAP",
        "use_case_tags": ["lap", "plot", "land", "mortgage", "secured"],
        "use_case_description": "Loan against owned plot or land parcel, generally with conservative LTV norms. Useful for high-ticket liquidity needs where land title is clear. Risk-adjusted pricing is higher than residential LAP.",
        "min_amount": 500_000,
        "max_amount": 20_000_000,
        "min_tenure_months": 36,
        "max_tenure_months": 180,
        "base_rate": 11.50,
        "max_rate": 15.00,
        "processing_fee_pct": 1.50,
        "processing_fee_floor_inr": 10_000,
        "ltv_cap": 0.50,
        "collateral_required": True,
        "min_credit_score": 700,
        "max_foir": 0.55,
        "negotiable": {
            "amount_delta_pct": 0.15,
            "rate_reduction_bps_max": 50,
            "rate_reduction_condition": {"min_credit_score": 750, "max_fraud_score": 30},
            "tenure_options_months": [60, 84, 120, 180],
        },
        "non_negotiable": ["ltv_cap", "min_credit_score", "max_foir", "processing_fee_floor_inr"],
    },
]


def _intent_for_loan(loan: dict) -> str:
    subtype = str(loan.get("subtype", "")).lower()
    parent = str(loan.get("parent_type", "")).lower()
    if "home" in parent:
        if "improvement" in subtype or "renovation" in subtype:
            return "home_improvement"
        return "home_purchase"
    if "vehicle" in parent:
        return "vehicle"
    if "education" in parent:
        return "education"
    if "business" in parent:
        return "business"
    if "medical" in subtype:
        return "medical"
    if "gold" in parent:
        return "personal"
    return "personal"


def _build_loan_product(loan: dict) -> dict:
    return {
        "loan_id": loan["loan_id"],
        "loan_name": loan["subtype"],
        "loan_type": loan["parent_type"],
        "intent_tags": [_intent_for_loan(loan)],
        "eligibility": {
            "min_credit_score": int(loan["min_credit_score"]),
            "max_credit_score": None,
            "min_net_income": 20000,
            "allowed_employment_types": ["salaried", "self_employed", "business_owner"],
            "min_age": 21,
            "max_age_at_maturity": 65,
            "collateral_required": bool(loan["collateral_required"]),
        },
        "product_terms": {
            "min_amount": int(loan["min_amount"]),
            "max_amount": int(loan["max_amount"]),
            "min_tenure_months": int(loan["min_tenure_months"]),
            "max_tenure_months": int(loan["max_tenure_months"]),
            "base_interest_rate_annual": float(loan["base_rate"]),
            "max_interest_rate_annual": float(loan["max_rate"]),
            "processing_fee_pct": float(loan["processing_fee_pct"]),
            "processing_fee_waivable": False,
            "moratorium_months_available": 0,
        },
        "negotiation_limits": {
            "max_rate_discount_bps": int(loan["negotiable"]["rate_reduction_bps_max"]),
            "max_amount_extension_pct": float(loan["negotiable"]["amount_delta_pct"]) * 100,
            "tenure_options_months": loan["negotiable"]["tenure_options_months"],
            "rate_reduction_condition": loan["negotiable"]["rate_reduction_condition"],
        },
        "non_negotiable": list(loan["non_negotiable"]),
        "use_case_description": loan["use_case_description"],
        "use_case_tags": list(loan["use_case_tags"]),
    }


LOAN_CATALOG = [_build_loan_product(loan) for loan in RAW_LOAN_CATALOG]

# Quick lookup by ID
LOAN_BY_ID: dict = {p["loan_id"]: p for p in LOAN_CATALOG}
